spring:
    application:
        name: security

    # 数据源
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/we_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
        password: admin
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        logSlowSql: true
        #最大连接数
        maxActive: 30
        #最小连接数
        minIdle: 5
        #获取连接的最大等待时间
        maxWait: 10000
        #解决mysql8小时的问题
        validationgQuery: SELECT 'X'
        #空闲连接的检查时间间隔
        timeBetweenEvictionRunsMillis: 60000
        #空闲连接最小空闲时间
        minEvictableIdleTimeMillis: 300000



    # Redis
    redis:
        host: 127.0.0.1
        password:
        max-active: 100
        max-idle: 10
        max-wait: 100000
        # 数据库索引 默认0
        database: 0
        port: 6379
        timeout: 3000


      # 文件大小上传配置
    multipart:
        max-file-size: 5Mb
        max-request-size: 5Mb


   # token过期时间（分钟）
    tokenExpireTime: 4320
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10

server:
    port: 8767 #启动端口

eureka:
  client:
      serviceUrl:
           defaultZone: http://localhost:8761/eureka/

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mettre.security.pojo
  typeEnumsPackage: com.mettre.security.pojo
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器MybatisPlusProperties
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


# Swagger界面内容配置
swagger:
  title: 微信权限
  description: 微信接口文档
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: security
    url: http://blog.exrick.cn
    email: 1052461392@qq.com